## Maintained by: github.com/tkrop/go-make@v0.0.140

engines:
  duplication:
    minTokenMatch: 50
    exclude_paths:
      - "**/*_test.go"
  revive:
    exclude_paths:
      - "**/zz_generated.*.go"
      - "**/mock_*_test.go"
      - "**/mock_*.go"
