name: Go Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.0

    - name: Build and tests
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        LANG: en_US.UTF-8
      # using --trace has a side effect on the the test output.
      run: make --file=config/Makefile.base all

    - name: Send coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ./build/test-all.cover
