name: Go Build
on: [push]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Test and lint
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: make --trace --file=config/Makefile.base test lint;

    - name: Send coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ./build/test.cover


  bash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Run Bash compatibility tests
      env:
        BASH_COMPAT: 3.2
      run: make --trace --file=config/Makefile.base test-self;


  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Run Bash compatibility tests
      run: |-
        make --version;
        make --trace --file=config/Makefile.base test-self;


  brew:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Set up npm tooling
      run: |-
        npm config set prefix "${RUNNER_TEMP}/npm-global";
        echo "${RUNNER_TEMP}/npm/bin" >> "${GITHUB_PATH}";

    - name: Run MacOS compatibility tests
      env:
        BASH_COMPAT: 3.2
      run: |-
        brew trust aws/tap; # fixes GitHub actions runner issue!
        make --version;
        make --file=config/Makefile.base test-self;


  macos-15:
    runs-on: macos-15
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Set up npm tooling
      run: |-
        npm config set prefix "${RUNNER_TEMP}/npm-global";
        echo "${RUNNER_TEMP}/npm/bin" >> "${GITHUB_PATH}";

    - name: Run MacOS compatibility tests
      env:
        BASH_COMPAT: 3.2
      run: |-
        brew trust aws/tap; # fixes GitHub actions runner issue!
        brew install make;
        export PATH="/opt/homebrew/opt/make/libexec/gnubin:${PATH}";
        make --version;
        make --trace --file=config/Makefile.base test-self;

  macos-26:
    runs-on: macos-26
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Set up npm tooling
      run: |-
        npm config set prefix "${RUNNER_TEMP}/npm-global";
        echo "${RUNNER_TEMP}/npm/bin" >> "${GITHUB_PATH}";

    - name: Run MacOS compatibility tests
      env:
        BASH_COMPAT: 3.2
      run: |-
        brew trust aws/tap; # fixes GitHub actions runner issue!
        brew install make;
        export PATH="/opt/homebrew/opt/make/libexec/gnubin:${PATH}";
        make --version;
        make --file=config/Makefile.base test-self;

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Release new version
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |-
        make --file=config/Makefile.base --trace version-release

    - name: Publish new version
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |-
        sleep 60 && make --file=config/Makefile.base --trace version-publish || true
