name: Go
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.21

    - name: Build and tests
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: make --file=Makefile.base --trace all

    - name: Send coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ./build/test-all.cover

    - name: Release and publish
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |-
        make --file=Makefile.base --trace release && \
        make --file=Makefile.base --trace publish
