name: Go Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.0

    - name: Release new version
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |-
        make --file=config/Makefile.base --trace release

    - name: Publish new version
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |-
        make --file=config/Makefile.base --trace publish || true
